# Generated by Django 3.2.7 on 2021-09-15 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Starleague', 'Starleague'), ('Proleague', 'Proleague'), ('Eventleague', 'Eventleague')], default='Starleague', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('most_race', models.CharField(choices=[('T', 'Terran'), ('P', 'Protoss'), ('Z', 'Zerg'), ('R', 'Random')], default='R', max_length=10)),
                ('signup_date', models.DateField(default=django.utils.timezone.now)),
                ('career', models.TextField(default='', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
